# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5974b52dc9c595aca3c77de3f7e54ccdebe1bb94b16fea225665af03a8950ba43819c72576b9d59fc74a55580010078043455f7ab76b1de8ae7871339fc4fcfb

test:
  secret_key_base: 61861a3ecadf0f7c9b6738b31e56dd357a3f0b082b1a776d01eb3f74f6bd6f794d87a97419abda17931402dc56d33a5c234bb991becd4f327ce4976a400eb6ee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
